#!/bin/bash
echo "🚀 Manual Flash Helper for Enhanced Firmware"
echo "============================================="
echo ""
echo "✅ Enhanced firmware ready: build/blink_led_enhanced.uf2 (76KB)"
echo ""
echo "🎯 Device Status:"
lsusb | grep 2e8a || echo "   ❌ No Pico device detected"
echo ""

if lsusb | grep -q "2e8a:000a"; then
    echo "✅ Device in BOOTSEL mode (2e8a:000a)"
    echo ""
    echo "🔧 OPTION 1: Try direct copy (if RPI-RP2 appears)"
    echo "   Check for: ls /media/*/RPI-RP2/ 2>/dev/null"
    echo "   If found: cp build/blink_led_enhanced.uf2 /media/*/RPI-RP2/"
    echo ""
    echo "🔧 OPTION 2: Wait for proper USB enumeration"
    echo "   The device may need a moment to fully enumerate"
    echo "   Try: picotool load build/blink_led_enhanced.uf2"
    echo ""
    echo "🔧 OPTION 3: Re-attach in Windows"
    echo "   In Windows PowerShell (Admin):"
    echo "   usbipd detach --busid 2-7"
    echo "   usbipd attach --wsl --busid 2-7"
    echo ""
elif lsusb | grep -q "2e8a:0003"; then
    echo "✅ Device in application mode (2e8a:0003)"
    echo "🔄 Need to reset to BOOTSEL mode first"
    echo ""
    echo "Try these commands:"
    echo "1. picotool reboot -f"
    echo "2. Wait 3 seconds"
    echo "3. Re-run this script"
    echo ""
else
    echo "❌ No Raspberry Pi Pico device found"
    echo ""
    echo "🔧 Troubleshooting:"
    echo "1. Check Windows: usbipd list | findstr '2e8a'"
    echo "2. Re-attach: usbipd attach --wsl --busid 2-X"
    echo "3. Verify: lsusb | grep 2e8a"
fi

echo ""
echo "📋 Available firmware files:"
ls -la build/blink_led_enhanced.* | grep -E '\.(uf2|bin|hex)$'
echo ""
echo "🎯 Goal: Flash enhanced firmware with runtime update capabilities!"